global:
  scrape_interval: 15s  # How often to scrape targets
  evaluation_interval: 15s  # How often to evaluate rules

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"  # Alertmanager running on Docker network

# Rule files for alerts
rule_files:
  - "/etc/prometheus/alert.rules.yml"  # Path to alert rules file

# Scrape configuration for Prometheus
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"  # Prometheus metrics

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]  # Use container name if using Docker network
      # OR
      - targets: ["172.31.10.151:9100"]  # Use private IP if not using Docker network 
